//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(IsNullable=false)]
public partial class DescriptorRecordSet {
    
    private DescriptorRecord[] descriptorRecordField;
    
    private DescriptorRecordSetLanguageCode languageCodeField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("DescriptorRecord")]
    public DescriptorRecord[] DescriptorRecord {
        get {
            return this.descriptorRecordField;
        }
        set {
            this.descriptorRecordField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DescriptorRecordSetLanguageCode LanguageCode {
        get {
            return this.languageCodeField;
        }
        set {
            this.languageCodeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class DescriptorRecord {
    
    private string descriptorUIField;
    
    private DescriptorName descriptorNameField;
    
    private DateCreated dateCreatedField;
    
    private DateRevised dateRevisedField;
    
    private DateEstablished dateEstablishedField;
    
    private AllowableQualifier[] allowableQualifiersListField;
    
    private string annotationField;
    
    private string historyNoteField;
    
    private string nLMClassificationNumberField;
    
    private string onlineNoteField;
    
    private string publicMeSHNoteField;
    
    private PreviousIndexingList previousIndexingListField;
    
    private EntryCombination[] entryCombinationListField;
    
    private SeeRelatedDescriptor[] seeRelatedListField;
    
    private string considerAlsoField;
    
    private PharmacologicalAction[] pharmacologicalActionListField;
    
    private TreeNumberList treeNumberListField;
    
    private Concept[] conceptListField;
    
    private DescriptorRecordDescriptorClass descriptorClassField;
    
    public DescriptorRecord() {
        this.descriptorClassField = DescriptorRecordDescriptorClass.Item1;
    }
    
    /// <uwagi/>
    public string DescriptorUI {
        get {
            return this.descriptorUIField;
        }
        set {
            this.descriptorUIField = value;
        }
    }
    
    /// <uwagi/>
    public DescriptorName DescriptorName {
        get {
            return this.descriptorNameField;
        }
        set {
            this.descriptorNameField = value;
        }
    }
    
    /// <uwagi/>
    public DateCreated DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <uwagi/>
    public DateRevised DateRevised {
        get {
            return this.dateRevisedField;
        }
        set {
            this.dateRevisedField = value;
        }
    }
    
    /// <uwagi/>
    public DateEstablished DateEstablished {
        get {
            return this.dateEstablishedField;
        }
        set {
            this.dateEstablishedField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AllowableQualifier", IsNullable=false)]
    public AllowableQualifier[] AllowableQualifiersList {
        get {
            return this.allowableQualifiersListField;
        }
        set {
            this.allowableQualifiersListField = value;
        }
    }
    
    /// <uwagi/>
    public string Annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <uwagi/>
    public string HistoryNote {
        get {
            return this.historyNoteField;
        }
        set {
            this.historyNoteField = value;
        }
    }
    
    /// <uwagi/>
    public string NLMClassificationNumber {
        get {
            return this.nLMClassificationNumberField;
        }
        set {
            this.nLMClassificationNumberField = value;
        }
    }
    
    /// <uwagi/>
    public string OnlineNote {
        get {
            return this.onlineNoteField;
        }
        set {
            this.onlineNoteField = value;
        }
    }
    
    /// <uwagi/>
    public string PublicMeSHNote {
        get {
            return this.publicMeSHNoteField;
        }
        set {
            this.publicMeSHNoteField = value;
        }
    }
    
    /// <uwagi/>
    public PreviousIndexingList PreviousIndexingList {
        get {
            return this.previousIndexingListField;
        }
        set {
            this.previousIndexingListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("EntryCombination", IsNullable=false)]
    public EntryCombination[] EntryCombinationList {
        get {
            return this.entryCombinationListField;
        }
        set {
            this.entryCombinationListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SeeRelatedDescriptor", IsNullable=false)]
    public SeeRelatedDescriptor[] SeeRelatedList {
        get {
            return this.seeRelatedListField;
        }
        set {
            this.seeRelatedListField = value;
        }
    }
    
    /// <uwagi/>
    public string ConsiderAlso {
        get {
            return this.considerAlsoField;
        }
        set {
            this.considerAlsoField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PharmacologicalAction", IsNullable=false)]
    public PharmacologicalAction[] PharmacologicalActionList {
        get {
            return this.pharmacologicalActionListField;
        }
        set {
            this.pharmacologicalActionListField = value;
        }
    }
    
    /// <uwagi/>
    public TreeNumberList TreeNumberList {
        get {
            return this.treeNumberListField;
        }
        set {
            this.treeNumberListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Concept", IsNullable=false)]
    public Concept[] ConceptList {
        get {
            return this.conceptListField;
        }
        set {
            this.conceptListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DescriptorRecordDescriptorClass.Item1)]
    public DescriptorRecordDescriptorClass DescriptorClass {
        get {
            return this.descriptorClassField;
        }
        set {
            this.descriptorClassField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class DescriptorName {
    
    private string stringField;
    
    /// <uwagi/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class DateCreated {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <uwagi/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <uwagi/>
    public string Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <uwagi/>
    public string Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class DateRevised {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <uwagi/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <uwagi/>
    public string Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <uwagi/>
    public string Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class DateEstablished {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <uwagi/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <uwagi/>
    public string Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <uwagi/>
    public string Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class AllowableQualifier {
    
    private QualifierReferredTo qualifierReferredToField;
    
    private string abbreviationField;
    
    /// <uwagi/>
    public QualifierReferredTo QualifierReferredTo {
        get {
            return this.qualifierReferredToField;
        }
        set {
            this.qualifierReferredToField = value;
        }
    }
    
    /// <uwagi/>
    public string Abbreviation {
        get {
            return this.abbreviationField;
        }
        set {
            this.abbreviationField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class QualifierReferredTo {
    
    private string qualifierUIField;
    
    private QualifierName qualifierNameField;
    
    /// <uwagi/>
    public string QualifierUI {
        get {
            return this.qualifierUIField;
        }
        set {
            this.qualifierUIField = value;
        }
    }
    
    /// <uwagi/>
    public QualifierName QualifierName {
        get {
            return this.qualifierNameField;
        }
        set {
            this.qualifierNameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class QualifierName {
    
    private string stringField;
    
    /// <uwagi/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class PreviousIndexingList {
    
    private string[] previousIndexingField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("PreviousIndexing")]
    public string[] PreviousIndexing {
        get {
            return this.previousIndexingField;
        }
        set {
            this.previousIndexingField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class EntryCombination {
    
    private ECIN eCINField;
    
    private ECOUT eCOUTField;
    
    /// <uwagi/>
    public ECIN ECIN {
        get {
            return this.eCINField;
        }
        set {
            this.eCINField = value;
        }
    }
    
    /// <uwagi/>
    public ECOUT ECOUT {
        get {
            return this.eCOUTField;
        }
        set {
            this.eCOUTField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ECIN {
    
    private DescriptorReferredTo descriptorReferredToField;
    
    private QualifierReferredTo qualifierReferredToField;
    
    /// <uwagi/>
    public DescriptorReferredTo DescriptorReferredTo {
        get {
            return this.descriptorReferredToField;
        }
        set {
            this.descriptorReferredToField = value;
        }
    }
    
    /// <uwagi/>
    public QualifierReferredTo QualifierReferredTo {
        get {
            return this.qualifierReferredToField;
        }
        set {
            this.qualifierReferredToField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class DescriptorReferredTo {
    
    private string descriptorUIField;
    
    private DescriptorName descriptorNameField;
    
    /// <uwagi/>
    public string DescriptorUI {
        get {
            return this.descriptorUIField;
        }
        set {
            this.descriptorUIField = value;
        }
    }
    
    /// <uwagi/>
    public DescriptorName DescriptorName {
        get {
            return this.descriptorNameField;
        }
        set {
            this.descriptorNameField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ECOUT {
    
    private DescriptorReferredTo descriptorReferredToField;
    
    private QualifierReferredTo qualifierReferredToField;
    
    /// <uwagi/>
    public DescriptorReferredTo DescriptorReferredTo {
        get {
            return this.descriptorReferredToField;
        }
        set {
            this.descriptorReferredToField = value;
        }
    }
    
    /// <uwagi/>
    public QualifierReferredTo QualifierReferredTo {
        get {
            return this.qualifierReferredToField;
        }
        set {
            this.qualifierReferredToField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class SeeRelatedDescriptor {
    
    private DescriptorReferredTo descriptorReferredToField;
    
    /// <uwagi/>
    public DescriptorReferredTo DescriptorReferredTo {
        get {
            return this.descriptorReferredToField;
        }
        set {
            this.descriptorReferredToField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class PharmacologicalAction {
    
    private DescriptorReferredTo descriptorReferredToField;
    
    /// <uwagi/>
    public DescriptorReferredTo DescriptorReferredTo {
        get {
            return this.descriptorReferredToField;
        }
        set {
            this.descriptorReferredToField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class TreeNumberList {
    
    private string[] treeNumberField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("TreeNumber")]
    public string[] TreeNumber {
        get {
            return this.treeNumberField;
        }
        set {
            this.treeNumberField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class Concept {
    
    private string conceptUIField;
    
    private ConceptName conceptNameField;
    
    private string cASN1NameField;
    
    private string registryNumberField;
    
    private string scopeNoteField;
    
    private string translatorsEnglishScopeNoteField;
    
    private string translatorsScopeNoteField;
    
    private string[] relatedRegistryNumberListField;
    
    private ConceptRelation[] conceptRelationListField;
    
    private Term[] termListField;
    
    private ConceptPreferredConceptYN preferredConceptYNField;
    
    /// <uwagi/>
    public string ConceptUI {
        get {
            return this.conceptUIField;
        }
        set {
            this.conceptUIField = value;
        }
    }
    
    /// <uwagi/>
    public ConceptName ConceptName {
        get {
            return this.conceptNameField;
        }
        set {
            this.conceptNameField = value;
        }
    }
    
    /// <uwagi/>
    public string CASN1Name {
        get {
            return this.cASN1NameField;
        }
        set {
            this.cASN1NameField = value;
        }
    }
    
    /// <uwagi/>
    public string RegistryNumber {
        get {
            return this.registryNumberField;
        }
        set {
            this.registryNumberField = value;
        }
    }
    
    /// <uwagi/>
    public string ScopeNote {
        get {
            return this.scopeNoteField;
        }
        set {
            this.scopeNoteField = value;
        }
    }
    
    /// <uwagi/>
    public string TranslatorsEnglishScopeNote {
        get {
            return this.translatorsEnglishScopeNoteField;
        }
        set {
            this.translatorsEnglishScopeNoteField = value;
        }
    }
    
    /// <uwagi/>
    public string TranslatorsScopeNote {
        get {
            return this.translatorsScopeNoteField;
        }
        set {
            this.translatorsScopeNoteField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RelatedRegistryNumber", IsNullable=false)]
    public string[] RelatedRegistryNumberList {
        get {
            return this.relatedRegistryNumberListField;
        }
        set {
            this.relatedRegistryNumberListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ConceptRelation", IsNullable=false)]
    public ConceptRelation[] ConceptRelationList {
        get {
            return this.conceptRelationListField;
        }
        set {
            this.conceptRelationListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Term", IsNullable=false)]
    public Term[] TermList {
        get {
            return this.termListField;
        }
        set {
            this.termListField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ConceptPreferredConceptYN PreferredConceptYN {
        get {
            return this.preferredConceptYNField;
        }
        set {
            this.preferredConceptYNField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ConceptName {
    
    private string stringField;
    
    /// <uwagi/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ConceptRelation {
    
    private string concept1UIField;
    
    private string concept2UIField;
    
    private ConceptRelationRelationName relationNameField;
    
    private bool relationNameFieldSpecified;
    
    /// <uwagi/>
    public string Concept1UI {
        get {
            return this.concept1UIField;
        }
        set {
            this.concept1UIField = value;
        }
    }
    
    /// <uwagi/>
    public string Concept2UI {
        get {
            return this.concept2UIField;
        }
        set {
            this.concept2UIField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ConceptRelationRelationName RelationName {
        get {
            return this.relationNameField;
        }
        set {
            this.relationNameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RelationNameSpecified {
        get {
            return this.relationNameFieldSpecified;
        }
        set {
            this.relationNameFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum ConceptRelationRelationName {
    
    /// <uwagi/>
    NRW,
    
    /// <uwagi/>
    BRD,
    
    /// <uwagi/>
    REL,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class Term {
    
    private string termUIField;
    
    private string stringField;
    
    private DateCreated dateCreatedField;
    
    private string abbreviationField;
    
    private string sortVersionField;
    
    private string entryVersionField;
    
    private string[] thesaurusIDlistField;
    
    private string termNoteField;
    
    private TermConceptPreferredTermYN conceptPreferredTermYNField;
    
    private TermIsPermutedTermYN isPermutedTermYNField;
    
    private TermLexicalTag lexicalTagField;
    
    private TermRecordPreferredTermYN recordPreferredTermYNField;
    
    /// <uwagi/>
    public string TermUI {
        get {
            return this.termUIField;
        }
        set {
            this.termUIField = value;
        }
    }
    
    /// <uwagi/>
    public string String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
    
    /// <uwagi/>
    public DateCreated DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <uwagi/>
    public string Abbreviation {
        get {
            return this.abbreviationField;
        }
        set {
            this.abbreviationField = value;
        }
    }
    
    /// <uwagi/>
    public string SortVersion {
        get {
            return this.sortVersionField;
        }
        set {
            this.sortVersionField = value;
        }
    }
    
    /// <uwagi/>
    public string EntryVersion {
        get {
            return this.entryVersionField;
        }
        set {
            this.entryVersionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ThesaurusID", IsNullable=false)]
    public string[] ThesaurusIDlist {
        get {
            return this.thesaurusIDlistField;
        }
        set {
            this.thesaurusIDlistField = value;
        }
    }
    
    /// <uwagi/>
    public string TermNote {
        get {
            return this.termNoteField;
        }
        set {
            this.termNoteField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermConceptPreferredTermYN ConceptPreferredTermYN {
        get {
            return this.conceptPreferredTermYNField;
        }
        set {
            this.conceptPreferredTermYNField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermIsPermutedTermYN IsPermutedTermYN {
        get {
            return this.isPermutedTermYNField;
        }
        set {
            this.isPermutedTermYNField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermLexicalTag LexicalTag {
        get {
            return this.lexicalTagField;
        }
        set {
            this.lexicalTagField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TermRecordPreferredTermYN RecordPreferredTermYN {
        get {
            return this.recordPreferredTermYNField;
        }
        set {
            this.recordPreferredTermYNField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum TermConceptPreferredTermYN {
    
    /// <uwagi/>
    Y,
    
    /// <uwagi/>
    N,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum TermIsPermutedTermYN {
    
    /// <uwagi/>
    Y,
    
    /// <uwagi/>
    N,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum TermLexicalTag {
    
    /// <uwagi/>
    ABB,
    
    /// <uwagi/>
    ABX,
    
    /// <uwagi/>
    ACR,
    
    /// <uwagi/>
    ACX,
    
    /// <uwagi/>
    EPO,
    
    /// <uwagi/>
    LAB,
    
    /// <uwagi/>
    NAM,
    
    /// <uwagi/>
    NON,
    
    /// <uwagi/>
    TRD,
    
    /// <uwagi/>
    Frelex,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum TermRecordPreferredTermYN {
    
    /// <uwagi/>
    Y,
    
    /// <uwagi/>
    N,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum ConceptPreferredConceptYN {
    
    /// <uwagi/>
    Y,
    
    /// <uwagi/>
    N,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum DescriptorRecordDescriptorClass {
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
public enum DescriptorRecordSetLanguageCode {
    
    /// <uwagi/>
    cze,
    
    /// <uwagi/>
    dut,
    
    /// <uwagi/>
    eng,
    
    /// <uwagi/>
    fin,
    
    /// <uwagi/>
    fre,
    
    /// <uwagi/>
    ger,
    
    /// <uwagi/>
    ita,
    
    /// <uwagi/>
    jpn,
    
    /// <uwagi/>
    lav,
    
    /// <uwagi/>
    por,
    
    /// <uwagi/>
    scr,
    
    /// <uwagi/>
    slv,
    
    /// <uwagi/>
    spa,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class AllowableQualifiersList {
    
    private AllowableQualifier[] allowableQualifierField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("AllowableQualifier")]
    public AllowableQualifier[] AllowableQualifier {
        get {
            return this.allowableQualifierField;
        }
        set {
            this.allowableQualifierField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class EntryCombinationList {
    
    private EntryCombination[] entryCombinationField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("EntryCombination")]
    public EntryCombination[] EntryCombination {
        get {
            return this.entryCombinationField;
        }
        set {
            this.entryCombinationField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class SeeRelatedList {
    
    private SeeRelatedDescriptor[] seeRelatedDescriptorField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("SeeRelatedDescriptor")]
    public SeeRelatedDescriptor[] SeeRelatedDescriptor {
        get {
            return this.seeRelatedDescriptorField;
        }
        set {
            this.seeRelatedDescriptorField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ConceptList {
    
    private Concept[] conceptField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Concept")]
    public Concept[] Concept {
        get {
            return this.conceptField;
        }
        set {
            this.conceptField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ConceptRelationList {
    
    private ConceptRelation[] conceptRelationField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ConceptRelation")]
    public ConceptRelation[] ConceptRelation {
        get {
            return this.conceptRelationField;
        }
        set {
            this.conceptRelationField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class PharmacologicalActionList {
    
    private PharmacologicalAction[] pharmacologicalActionField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("PharmacologicalAction")]
    public PharmacologicalAction[] PharmacologicalAction {
        get {
            return this.pharmacologicalActionField;
        }
        set {
            this.pharmacologicalActionField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class RelatedRegistryNumberList {
    
    private string[] relatedRegistryNumberField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("RelatedRegistryNumber")]
    public string[] RelatedRegistryNumber {
        get {
            return this.relatedRegistryNumberField;
        }
        set {
            this.relatedRegistryNumberField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class TermList {
    
    private Term[] termField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("Term")]
    public Term[] Term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/nlmdescriptorrecordset_20160101", IsNullable=false)]
public partial class ThesaurusIDlist {
    
    private string[] thesaurusIDField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("ThesaurusID")]
    public string[] ThesaurusID {
        get {
            return this.thesaurusIDField;
        }
        set {
            this.thesaurusIDField = value;
        }
    }
}
